### ISSUE TITLE
stalker will not connect to url in the format of http:\\www. xxx.xxx.xxx:portnumber\c

### ISSUE THREAD

**Issue by ians325** [kodi-pvr/pvr.stalker#106]
stalker will not connect to url in the format of http:\\www. xxx.xxx.xxx:portnumber\c

**Comment by Jalle19** [comment]
That is not in any way a valid URL. Are you sure you wrote it correctly?

**Comment by ians325** [comment]
http:\\www.s****-**.*****:2****\c

**Comment by ians325** [comment]
\\

**Comment by Jalle19** [comment]
Please, use proper URLs...
