### ISSUE TITLE
Client failing with CVideoPlayer::OpenInputStream - error opening pvr://channel...

### ISSUE THREAD

**Issue by npcomplete13** [kodi-pvr/pvr.stalker#116]
Platform: LibreElec 9.0 (RK3399)

Error Occurrences:

	Line 673: 17:02:11.565 T:545204986016   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.stalker_241781412.pvr]
	Line 715: 17:02:13.432 T:545204986016   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.stalker_241781412.pvr]

See detailed Log here: https://pastebin.com/R6kzF81W

**Comment by ksooo** [comment]
Fixed with #118
