### ISSUE TITLE
Connection timeout greater than 15

### ISSUE THREAD

**Issue by IvanJosipovic** [kodi-pvr/pvr.stalker#13]
Hi,

Can you please allow the settings to set a connection timeout greater than 15s. My current provider requires 60s.

Thanks!

**Comment by kenji123** [comment]
Okay

**Comment by psyc0n** [comment]
I would suggest allowing perhaps up to 120 seconds  in case the servers ever require more of an allowance in the future..

**Comment by kenji123** [comment]
fixed in #21. specifically e2d1cf0.

you can also set connection timeout to zero to disable it completely
