### ISSUE TITLE
Add a "user agent" setting

### ISSUE THREAD

**Issue by rexio8** [kodi-pvr/pvr.stalker#143]
Please add a text field to the settings of Stalker Client, so that one can change the default user_agent reported by the add on. More and more live tv providers seem to block the default (old) one. Please add this change to the Leia and Matrix versions.

**Comment by phunkyfish** [comment]
This add-on currently has no maintainer so unless someone with it working steps up and implements this it is unlikely to happen.

**Comment by rexio8** [comment]
Thanks for the information. So closing this issue as it's not likely going to happen.

**Comment by phunkyfish** [comment]
I would leave the issue open so someone interested in extending the add-on would possibly see it.
