### ISSUE TITLE
Audio drops out

### ISSUE THREAD

**Issue by Barry523** [kodi-pvr/pvr.stalker#16]
I have been using this on kodi 15 RC 2 on both my PC and an Amazon fire tv stick and I've found the same issue on both.

I have connected to both the NFPS and Rocket servers using this and on every channel I experience audio drop outs. They only last a split second but occur every 10 seconds or so. Both of the servers channels sets work fine when viewed on Kodi through IPTV stalker addon.

I have tried Kodi nightly builds as well as 3 seperate builds of this PVR.

Has anyone else had this problem and knows of a fix please?

**Comment by Barry523** [comment]
The release of Kodi 15 Isengaard has not changed a thing

**Comment by kenji123** [comment]
This add-on does not open or manipulate the channel streams in anyway. Either it's the stream from the provider, Kodi itself, hardware related, or some combination of the former.

**Comment by Jalle19** [comment]
There's a bug report on trac about this, some fixes are coming up shortly.
