### ISSUE TITLE
Characters With Accents in epg

### ISSUE THREAD

**Issue by Blackbear199** [kodi-pvr/pvr.stalker#20]
Hi,

Benn fighting with this problem of Spanish Accents,looking in the log I see
[code]16:55:15 T:7480   DEBUG: AddOnLog: Stalker Client: XMLTV::ReadChannels: id=I251.309214043.microsoft.com | displayName=Discovery en Espa�ol
16:55:15 T:7480   DEBUG: AddOnLog: Stalker Client: XMLTV::ReadChannels: id=I253.176955571.microsoft.com | displayName=History en Espa�ol
[/code]
Could you comment on this,i think stalker its reconizing the characters,its suppost to be Español
Tried changing my epg to UTF-8 from iso-8859-1 but it messed up the epg(most channels missing,no color in guide).Changed back to ISO-8859-1 and all good again.
Does pvr stalker expect the epg to be ISO-8859-1?
Thks.

**Comment by kenji123** [comment]
Can you can provide a sample xml file, so that I can check this out further?

**Comment by Blackbear199** [comment]
Hi,
if you try to import the included epg file and look for the Discovery en Español(channel 845) u will see it does not show in epg.if you search the xml file for I251.309214043.microsoft.com(its the above channel) you will that when I pull it with mc2xml I mapped it in the .ren file to Discovery en Espa&#241;ol which is the correct way I believe because of the accent.i also tried mapping it with the accent,both ways it does not show.
thanks
https://mega.nz/#!D4RVlLxD!rRJPUyqxFwGo3g0BTVq1Gd10_lszsFBa2rQx3ybYssQ

**Comment by Blackbear199** [comment]
I mapped it to & # 2 4 1 ; (no spaces) for the accent.in above post it changed it when I submitted reply.

**Comment by Blackbear199** [comment]
Hi,
I finally had a time to have another look at this.turns out there's nothing wrong(well on your end).when I changed to uft-8 before I missed a ampersand(wasn't & a m p ; no spaces) and it would crash epg parsing.
sorry to bother you with this and you can close it.
thanks
BB

**Comment by kenji123** [comment]
That's ok. I need to review parts of the code that are related to this anyway; will keep this in mind.
