### ISSUE TITLE
Update 21.1.0 Stalker crashed on Windows

### ISSUE THREAD

**Issue by DWH-WFC** [kodi-pvr/pvr.stalker#227]
Hello from Germany.
Since the update last night, Kodi keeps crashing shortly after starting.
It always freezes briefly when Stalker starts and then crashes.
It worked fine with the last version. A new installation of Kodi and Stalker produces the same result. When upgrading from Kodi 20.5 to 21.0, it works until the next Kodi restart, then Kodi also crashes when loading the client.

[kodi.log](https://github.com/user-attachments/files/15944178/kodi.log)
[kodi_crashlog-21.0 Git_20240406-60c4500054-20240623-122122.dmp](https://github.com/user-attachments/files/15944179/kodi_crashlog-21.0.Git_20240406-60c4500054-20240623-122122.dmp)
[kodi_stacktrace-21.0 Git_20240406-60c4500054-20240623-122122.txt](https://github.com/user-attachments/files/15944180/kodi_stacktrace-21.0.Git_20240406-60c4500054-20240623-122122.txt)

**Comment by phunkyfish** [comment]
Could you create a full debug log capturing the crash please?

https://kodi.wiki/view/Log_file

**Comment by DWH-WFC** [comment]
I hope that is correct.
I reinstalled Kodi and then installed the Stalker Client via the Kodi repo. Immediately after the installation, Kodi crashed again.
[kodi.log](https://github.com/user-attachments/files/15944278/kodi.log)
[kodi_crashlog-21.0 Git_20240406-60c4500054-20240623-130841.dmp](https://github.com/user-attachments/files/15944279/kodi_crashlog-21.0.Git_20240406-60c4500054-20240623-130841.dmp)
[kodi_stacktrace-21.0 Git_20240406-60c4500054-20240623-130841.txt](https://github.com/user-attachments/files/15944280/kodi_stacktrace-21.0.Git_20240406-60c4500054-20240623-130841.txt)

**Comment by DWH-WFC** [comment]
Here are the 2 logs when I use a new installation and update from Stalker 21.0.1 to 21.1.0.

The Version 21.0.1 works fine.

[kodi.log](https://github.com/user-attachments/files/15944380/kodi.log)
[kodi.old.log](https://github.com/user-attachments/files/15944381/kodi.old.log)

**Comment by phunkyfish** [comment]
Can you try two things?

First try to install 21.0.1 of the addon and see if the crash goes away.

Secondly, try deleting the `addon_data/pvr.stalker` (please back it up first) and see if the behaviour changes. You’ll need to reconfigure the addon when you do this. If it doesn’t work I might get you to sen some your backup to see if I can reproduce the crash.

**Comment by MARIOSW226** [comment]
Try installing the old version 21.0.0, disable automatic updates. That's what I did, and it works.

**Comment by phunkyfish** [comment]
> Try installing the old version 21.0.0, disable automatic updates. That's what I did, and it works.

This will make the addon functional but will not help figure out that the issue is. Out of interest, are you also on Windows?

**Comment by Sachin736** [comment]
I installed new version on windows, it crashed and can't even add address and url.

**Comment by phunkyfish** [comment]
Is it only windows that has this problem? Has anyone uncovered issues on another platform?

**Comment by phunkyfish** [comment]
> I installed new version on windows, it crashed and can't even add address and url.

Is this a fresh install or an update on a previous version?

**Comment by Sachin736** [comment]
Fresh install Kodi omega 21.0 and stalker client 21.1.0. When pvr client installed kodi crashed.

**Comment by ppoeps4** [comment]
stalker client 21.1.0 crash.On windows.

**Comment by Sachin736** [comment]
Yes. When you install it kodi closes automatically.

**Comment by phunkyfish** [comment]
Can someone try on a non windows platform? If it doesn’t crash there might help narrow it down.

**Comment by phunkyfish** [comment]
Some test settings.xml files might also help for testing.

**Comment by DWH-WFC** [comment]
So with 21.0.1 it works great. After an update to version 21.1.0, Kodi crashes immediately. The migration of the settings.xml is not even carried out. A notification appears in the top right that the Stalker Client has started and then causes Kodi to crash. In the test, all 5 providers were completely filled out and worked without problems. But regardless of whether it is an existing or new installation of Kodi, the behavior is the same. If I copy the contents of the 21.0.1.zip back into the "addons" folder after the crash, the client works again without problems.

[21.0.1 to 21.1.0.log](https://github.com/user-attachments/files/15958168/21.0.1.to.21.1.0.log)

**Comment by DWH-WFC** [comment]
The settings.xml remains unchanged. I can use it again immediately after copying version 21.0.1 back in.

In the log from line 706 I noticed that it is trying to read the settings.xml but it cannot find any content even though it is available.

**Comment by DWH-WFC** [comment]
> Is it only windows that has this problem? Has anyone uncovered issues on another platform?

I have just tested version 21.1.0 again on Android TV. It works without any problems there

**Comment by MARIOSW226** [comment]
> > Try installing the old version 21.0.0, disable automatic updates. That's what I did, and it works.
> 
> This will make the addon functional but will not help figure out that the issue is. Out of interest, are you also on Windows?

Yes I am on Windows. But with my phone v21.1.0 works well. I think that it's only on Windows that it's crash.

**Comment by phunkyfish** [comment]
> > > Try installing the old version 21.0.0, disable automatic updates. That's what I did, and it works.
> > 
> > 
> > This will make the addon functional but will not help figure out that the issue is. Out of interest, are you also on Windows?
> 
> Yes I am on Windows. But with my phone v21.1.0 works well. I think that it's only on Windows that it's crash.

Thanks for confirming

**Comment by phunkyfish** [comment]
> So with 21.0.1 it works great. After an update to version 21.1.0, Kodi crashes immediately. The migration of the settings.xml is not even carried out. A notification appears in the top right that the Stalker Client has started and then causes Kodi to crash. In the test, all 5 providers were completely filled out and worked without problems. But regardless of whether it is an existing or new installation of Kodi, the behavior is the same. If I copy the contents of the 21.0.1.zip back into the "addons" folder after the crash, the client works again without problems.
> 
> [21.0.1 to 21.1.0.log](https://github.com/user-attachments/files/15958168/21.0.1.to.21.1.0.log)

So there is no instance-settings-1.xml created? That likely means the crash is happening as part of the settings migration. I can create a testbuild for you to try with some extra logging to try and figure out where the crash occurs.

**Comment by DWH-WFC** [comment]
Yes, exactly, no instance settings are created because the crash happens beforehand.
Yes, I can test the test build if you send it to me.

**Comment by phunkyfish** [comment]
> Yes, exactly, no instance settings are created because the crash happens beforehand. Yes, I can test the test build if you send it to me.

Please try these testbuilds on windows and post a full debug log. If the crash is happening during migration you should see debug log entries starting with `ZZ`

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/1/artifacts

**Comment by Sachin736** [comment]
Could not parse type "Setting.Details.SettingList"
[kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)

**Comment by phunkyfish** [comment]
> Could not parse type "Setting.Details.SettingList" [kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)

That’s an info log and a not a debug log so none of the new logging will be printed I’m afraid. Can you restart in debug mode and post another log please? 

`Setting.Details.SettingList` is JSONRPC related so safe to ignore. Plus it’s in both log files.

**Comment by Sachin736** [comment]
> > Could not parse type "Setting.Details.SettingList" [kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)
> 
> That’s an info log and a not a debug log so none of the new logging will be printed I’m afraid. Can you restart in debug mode and post another log please?
> 
> `Setting.Details.SettingList` is JSONRPC related so safe to ignore. Plus it’s in both log files.

Check these two, it's in debug mode
[kodi.old.log](https://github.com/user-attachments/files/15966111/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/15966115/kodi.log)

**Comment by phunkyfish** [comment]
> > > Could not parse type "Setting.Details.SettingList" [kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)
> > 
> > 
> > That’s an info log and a not a debug log so none of the new logging will be printed I’m afraid. Can you restart in debug mode and post another log please?
> > `Setting.Details.SettingList` is JSONRPC related so safe to ignore. Plus it’s in both log files.
> 
> Check these two, it's in debug mode [kodi.old.log](https://github.com/user-attachments/files/15966111/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15966115/kodi.log)

Your case appears to be different. If you look in `userdata\addon_data\pvr.stalker` I assume you have an `instance_setttings-1.xml` file? Which mean the settings migration has already run and so none of the new log statements will print. This could mean the crash is your case happens after settings load.

**Comment by Sachin736** [comment]
> > > > Could not parse type "Setting.Details.SettingList" [kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)
> > > 
> > > 
> > > That’s an info log and a not a debug log so none of the new logging will be printed I’m afraid. Can you restart in debug mode and post another log please?
> > > `Setting.Details.SettingList` is JSONRPC related so safe to ignore. Plus it’s in both log files.
> > 
> > 
> > Check these two, it's in debug mode [kodi.old.log](https://github.com/user-attachments/files/15966111/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15966115/kodi.log)
> 
> Your case appears to be different. If you look in `userdata\addon_data\pvr.stalker` I assume you have an `instance_setttings-1.xml` file? Which mean the settings migration has already run and so none of the new log statements will print. This could mean the crash is your case happens after settings load.

Yes crash happened when stalker client loads.
![2024-06-25 (1)](https://github.com/kodi-pvr/pvr.stalker/assets/26081202/7f75ee9b-a95e-41e2-93bc-ce62dd038808)

**Comment by nagysifa** [comment]
Having the same isues on my Windows 10 ( 64bit and 32 bit ) installations ... the same config ( copyed the complete "portable_data" folder to each Windows ) works as expected on both of my Windows 11 configurations.

**Comment by Sachin736** [comment]
> > > > Could not parse type "Setting.Details.SettingList" [kodi.old.log](https://github.com/user-attachments/files/15964332/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15964333/kodi.log)
> > > 
> > > 
> > > That’s an info log and a not a debug log so none of the new logging will be printed I’m afraid. Can you restart in debug mode and post another log please?
> > > `Setting.Details.SettingList` is JSONRPC related so safe to ignore. Plus it’s in both log files.
> > 
> > 
> > Check these two, it's in debug mode [kodi.old.log](https://github.com/user-attachments/files/15966111/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15966115/kodi.log)
> 
> Your case appears to be different. If you look in `userdata\addon_data\pvr.stalker` I assume you have an `instance_setttings-1.xml` file? Which mean the settings migration has already run and so none of the new log statements will print. This could mean the crash is your case happens after settings load.

Also, When the addon is installed it crashed. I can't provide url and mac address for it.

![2024-06-25](https://github.com/kodi-pvr/pvr.stalker/assets/26081202/f149ec9a-95b8-4a0f-9161-fe01ebdb4129)

In userdata\addon_data\ folder pvr.stalker is not there. No inputs is given.
Only addons folder has pvr.stalker

**Comment by Sachin736** [comment]
> Having the same isues on my Windows 10 ( 64bit and 32 bit ) installations ... the same config ( copyed the complete "portable_data" folder to each Windows ) works as expected on both of my Windows 11 configurations.

Yes. In Windows 11 it works fine.

**Comment by DWH-WFC** [comment]
For me it crashes on my PC under Windows 11. I tested it on my laptop with Windows 11 and it works there.
I'm going to try the test build now.

**Comment by DWH-WFC** [comment]
So I've now done 2 tests.
Both with a new installation of Kodi without additional add-ons.
1st test
Installation of PVR 21.1.1.zip without existing settings.xml

2nd test
Installation of PVR 21.0.1.zip created settings.xml and entered access (works). Updated PVR 21.1.1.zip.
Crashes immediately. (Access URL obscured with XXXXXXXX)

[kodi_new_Install-PVR_Install_from_zip.log](https://github.com/user-attachments/files/15968611/kodi_new_Install-PVR_Install_from_zip.log)
[Update_from_21.0.1_to_21.1.1.log](https://github.com/user-attachments/files/15968612/Update_from_21.0.1_to_21.1.1.log)

**Comment by phunkyfish** [comment]
> So I've now done 2 tests. Both with a new installation of Kodi without additional add-ons. 1st test Installation of PVR 21.1.1.zip without existing settings.xml
> 
> 2nd test Installation of PVR 21.0.1.zip created settings.xml and entered access (works). Updated PVR 21.1.1.zip. Crashes immediately. (Access URL obscured with XXXXXXXX)
> 
> [kodi_new_Install-PVR_Install_from_zip.log](https://github.com/user-attachments/files/15968611/kodi_new_Install-PVR_Install_from_zip.log) [Update_from_21.0.1_to_21.1.1.log](https://github.com/user-attachments/files/15968612/Update_from_21.0.1_to_21.1.1.log)

Thanks for the testing so far. The crash appears to happen after settings are loaded, maybe when authenticating. The strange thing is that it appears to load default settings and not do a migration, not sure why. I've added more logging, could you test again?

New testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/2/artifacts

**Comment by DWH-WFC** [comment]
Tested in the same way as before.
See order above.

[kodi_new_Install-PVR_Install_from_zip.log](https://github.com/user-attachments/files/15969421/kodi_new_Install-PVR_Install_from_zip.log)
[Update_from_21.0.1_to_21.1.1.log](https://github.com/user-attachments/files/15969423/Update_from_21.0.1_to_21.1.1.log)

**Comment by phunkyfish** [comment]
> Tested in the same way as before. See order above.
> 
> [kodi_new_Install-PVR_Install_from_zip.log](https://github.com/user-attachments/files/15969421/kodi_new_Install-PVR_Install_from_zip.log) [Update_from_21.0.1_to_21.1.1.log](https://github.com/user-attachments/files/15969423/Update_from_21.0.1_to_21.1.1.log)

Brilliant, we are getting closer. Can you run the same test with these testbuilds?https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/3/artifacts

**Comment by Sachin736** [comment]
[kodi.old.log](https://github.com/user-attachments/files/15971637/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/15971641/kodi.log)

**Comment by phunkyfish** [comment]
> [kodi.old.log](https://github.com/user-attachments/files/15971637/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15971641/kodi.log)

Thanks again, closer still. More testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/4/artifacts

The builds should be there in a few minutes, just building now.

**Comment by Sachin736** [comment]
[kodi.old.log](https://github.com/user-attachments/files/15972475/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/15972478/kodi.log)

**Comment by phunkyfish** [comment]
> [kodi.old.log](https://github.com/user-attachments/files/15972475/kodi.old.log) [kodi.log](https://github.com/user-attachments/files/15972478/kodi.log)

Very strange. So it looks like the problem is with the mutex used for authentication, or the thread is blocked somewhere. I can try cleaning up that code a bit and/or fix what’s blocking it. Weird that it only causes a problem on windows.

**Comment by DWH-WFC** [comment]
Do you still need the final tests from me? Or have you found the error now?

**Comment by phunkyfish** [comment]
Good for now thanks. I need to figure out where’s it’s blocking and add more logging. Will let you know when I have another build to test.

**Comment by phunkyfish** [comment]
> Do you still need the final tests from me? Or have you found the error now?

Ok, one more set of testbuilds I need a debug log for: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/5/artifacts

**Comment by DWH-WFC** [comment]
Thank you for your work. Just let us know if you want us to test something.

**Comment by DWH-WFC** [comment]
> > Do you still need the final tests from me? Or have you found the error now?
> 
> Ok, one more set of testbuilds I need a debug log for: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/5/artifacts

No Problem.

**Comment by DWH-WFC** [comment]
Here are the latest tests.
The procedure is the same as the last ones I did.

[kodi_new_Install-PVR_Install_from_zip.log](https://github.com/user-attachments/files/15984484/kodi_new_Install-PVR_Install_from_zip.log)
[Update_from_21.0.1_to_21.1.1.log](https://github.com/user-attachments/files/15984486/Update_from_21.0.1_to_21.1.1.log)

**Comment by phunkyfish** [comment]
Ok, first attempt at a fix. Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.stalker/detail/PR-229/6/artifacts

Will need a full debug log as usual.

**Comment by Sachin736** [comment]
[kodi.old.log](https://github.com/user-attachments/files/15986768/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/15986770/kodi.log)
[only pvr addon.log](https://github.com/user-attachments/files/15986854/only.pvr.addon.log)

**Comment by phunkyfish** [comment]
Ok, no change. I’m going to ask someone who develops on windows to try running it and see if they can find the cause of the crash.

**Comment by phunkyfish** [comment]
Can someone try this using the latest version of the add-on but instead a nightly version of kodi omega, on a non working windows device/PC?

https://mirrors.kodi.tv/nightlies/

**Comment by Sachin736** [comment]
> Can someone try this using the latest version of the add-on but instead a nightly version of kodi omega, on a non working windows device/PC?
> 
> https://mirrors.kodi.tv/nightlies/

Works for KodiSetup-20240626-7508b879-Omega-x64 and pvr 21.1.0
[kodi.log](https://github.com/user-attachments/files/16038922/kodi.log)

**Comment by phunkyfish** [comment]
Ok, then it looks like it might be a runtime issue.

Can you revert to the released kodi version, and then run it to prove it crashes and if so, then try installing https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170, to see if it goes away?

It might be that the newer version of the addon is built with a newer runtime and systems with an older runtime then crash.

**Comment by Sachin736** [comment]
> Ok, then it looks like it might be a runtime issue.
> 
> Can you revert to the released kodi version, and then run it to prove it crashes and if so, then try installing https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170, to see if it goes away?
> 
> It might be that the newer version of the addon is built with a newer runtime and systems with an older runtime then crash.

Yes. It needs Microsoft Visual C++ Redistributable Version 14.40.33810.0 to run.

**Comment by Sachin736** [comment]
Now it's working fine.

**Comment by nagysifa** [comment]
I can confirm, this resolved the isue on x86/x64 Windows 10 installations ... even the newest version of "inputstream.adaptive" is working now ( probobly built with the same newer runtime ). Thank You!

**Comment by phunkyfish** [comment]
Excellent, thanks for all the testing!

**Comment by DWH-WFC** [comment]
Now it's working fine 👌 Thank you @all

**Comment by flubshi** [comment]
@phunkyfish are changes required in the addon source to fix this problem? I am asking, because users reporting the same for [pvr.waipu](https://github.com/flubshi/pvr.waipu/issues/340)

**Comment by phunkyfish** [comment]
> @phunkyfish are changes required in the addon source to fix this problem? I am asking, because users reporting the same for [pvr.waipu](https://github.com/flubshi/pvr.waipu/issues/340)

No changes required in the addon. Users can install the latest VC++ redistributable or use an Omega nightly of kodi.

**Comment by phunkyfish** [comment]
Pinned issue created for other users who come across this problem: https://github.com/kodi-pvr/pvr.stalker/issues/230

Also updated on forum post for v21.1.0: https://forum.kodi.tv/showthread.php?tid=377974&pid=3202625#pid3202625
