### ISSUE TITLE
[Feature Request] Record TV (DVR feature) save video stream to local disk

### ISSUE THREAD

**Issue by Hedda** [kodi-pvr/pvr.stalker#42]
I like to make a feature suggestion, and that is the add a recording functionality into this PVR client addon.

The ability to "record to disk" from a user experince. In function be able act a DVR (Digital Video Recorder), to save individual video streams to local disk directory/folder. Preferably even save as video files in MPEG-TS (.TS) format just like real DVRs. 

This ability to record can also add more features which have dependency on recording, like the ability to "Pause" and "rewind" Live TV if could add the possibility to continusly record to a series of temporary files in a look, again just like a read DVR.

All such a function is normally located and dependent in the PVR backend instead of the PVR client addon, but this PVR client addon is somewhat unique in that it connects to the content streams directly, streaming directly from, so it does not go through a third-party PVR backend which can bring such recording functionality. And in addition it would be very nice to have the ability for the video files to be saved locally directlly on an Android device instead of on the PVR backend.

**Comment by MartijnKaijser** [comment]
this should be a backend function

**Comment by Hedda** [comment]
@MartijnKaijser sorry to see you closing this without first researching the issue at hand

It is just not possible to say that this is a PVR backend issue on a PVR client that does not actually have a PVR backend, which the Stalker client addon for Kodi indeed does not. The Stalker client addon connect direct to the content, so you do not instead a matching third-party PVR backend software at home to use it. For all intended purposes from a end-user experience the client addon is stand-alone and works without a PVR backend installed in your home, which means that you can not initiate record from the IPTV Simple Client addon.

Again, the Stalker client addon (and a few other PVR client addons) are in a somewhat unique situation that it is stand-alone and does not have or need a matching PVR backend software installed at home, and instead it direct connect to the content streams on the internet.

As such  the Stalker client addon for Kodi does not fit within the classic client <=> backend concept that other PVR addons for Kodi relies on.

**Comment by psyc0n** [comment]
with this plugin it recording be a backend function.  the backend server is a remote server and does not host recordings for all of its clients, it merely streams the live content.  recordings must be handled on the client side. so simply saving the stream to disk  would be the  only way to record.

**Comment by Hedda** [comment]
Here is a fork of the Simple IPTV PVR client with code which features a simple recording feature which adds timeshifting functionality:

https://github.com/simphax/pvr.iptvsimple

@MartijnKaijser  would you reject a pull request for such features to the Stalker (or native HDHomeRun) PVR client addons too? Please note that your Nate posted in native HDHomeRun PVR client addon forum thread not long ago and requested this feature himself.

Point is for this addons to have this capability nativly is just these few unique stand-alone client addons without the need to use a backend.

**Comment by Hedda** [comment]
@opdenkamp @hudokkow @metaron-uk what are your opinions on having such native features in these types of PVR client addons which do not use a backend?

**Comment by Jalle19** [comment]
Can you please not post the same thing everywhere? One thread is enough.

**Comment by hudokkow** [comment]
I don't have an opinion other than it feels kinda shady unless a backend is involved. PVR add-ons are meant to be Kodi's bridge to a backend, be it physical or virtual. In my opinion, add-ons should only support capabilities that respective backend already provides.

That's not so simple with IPTVSimple. Its almost 100% guaranteed that one does not own or have any rights to the content being streamed. IPTVSimple works mostly with streams *found* all over the place and adding record/dump capability to it feels wrong.

Someone can easily think we're in the business of providing tools for piracy. We're not!
Besides, I'm fairly certain we already turned down a PR - see https://github.com/rkubera/pvr.iptvsimple/commit/a7087fd5770ab1d55ab724e3095365b6341816a3 - that added recording capabilities to IPTVSimple but I can't find it now.

BTW @simphax, the correct way to fork and add functionality(ies) not accepted on master is to fork, rename the add-on (keeping copyright notices to original developers) and add said functionalities.

Keeps users from confusing the official add-on with the one that's not official. It also prevents add-on clashes and the occasional version mess.

**Comment by CrazeeGhost** [comment]
Another vote for adding this capability into the add-on.
