### ISSUE TITLE
Linux PVR Stalker Client with NFPS

### ISSUE THREAD

**Issue by jbmediabox** [kodi-pvr/pvr.stalker#46]
I am a newbie and sorry if i am posting this question is a wrong forum.

I am running ubuntu 15.04 and Kodi 15.2 . I am looking for a PVR client that can work with the new NFPS setting i.e. user id and password.

I have been told that i need to build my own  pvr stalker client since there is none released yet for ubuntu/linux

has anyone compiled the new pvr.stalker and if not then how can i do that 

Thanks.
jb

**Comment by kenji123** [comment]
See: http://forum.kodi.tv/showthread.php?tid=219166
