### ISSUE TITLE
Incompatible with certain stalker middleware server

### ISSUE THREAD

**Issue by psyc0n** [kodi-pvr/pvr.stalker#50]
Server works fine on AVOV and MAG devices, not sure why pvr.stalker is having issues with the handshake, seems to not like the cookies or something. I know you dont care about specific servers, but it seems that pvr.stalker is generally missing something  if MAG devices  can connect and it cant.

server you can test on is iptvsubs.is  You can replicate issue by signing up at their site, there is a free trial.,, sign up as a MAG device, not kodi (their own kodi app uses a whole different login system ). I have logins if you need them, pm me on the kodi forum

**Comment by kenji123** [comment]
That service may be using an older or modified version of Stalker Middleware, which is outside the scope of this add-on.
