### ISSUE TITLE
Add-on fails to build on jenkins win32

### ISSUE THREAD

**Issue by hudokkow** [kodi-pvr/pvr.stalker#62]
> C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition
c:\jenkins\slave\workspace\win-32\project\cmake\addons\build\libxml2\src\libxml2\config.h(99): note: see previous definition of 'snprintf'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration

Full build log: http://jenkins.kodi.tv/job/WIN-32/9005/consoleText

**Comment by kenji123** [comment]
Was able to recreate the error, and it compiles ok now.

Just for clarity: the source of the problem was with <= v2.9.3 of libxml2 in libxml2/win32/VC10/config.h (which is copied to libxml2/config.h) did not have a check for _MSC_VER < 1900 before defining snprintf.
